### ISSUE TITLE
Missing dependency FDSQueueNonEmpty

### ISSUE THREAD

**Issue by markfirmware** [emdonahue/SmallKanren#2]
Is SmallKanren ready to use in Pharo 9?

I am interested in trying SmallKranen in [gtoolkit](https://gtoolkit.com) (64 bit linux) and gtoolkit is based on pharo 9. After using Iceberg to load Cons and FunctionalDataStructures, there is a missing dependency (FDSQueueNonEmpty) when I try to load SmallKanren.

**Comment by emdonahue** [comment]
I'm going to close this on the assumption that it sounds like it's probably working now, but feel free to open another issue if there's still a problem. Also feel free to get in touch if you want to talk about your use case, since there are undocumented features that might be helpful if you run into an issue.
