### ISSUE TITLE
Installation fails with "NotFound: revspec 'master' not found"

### ISSUE THREAD

**Issue by Toni-zgz** [emdonahue/SmallKanren#4]
I tried to install it in Pharo 11.0
```pharo
Metacello new
	  baseline: 'SmallKanren';
	  repository: 'github://emdonahue/SmallKanren';
	  load.
```
But I've got a "NotFound: revspec 'master' not found". What can i do to resolve this issue?

**Comment by emdonahue** [comment]
Thanks for the report. 

Unfortunately Pharo's Git integration has changed so much since I was last developing this project that I no longer know how projects are expected to be distributed. I assume you can use whatever is the current generic Iceberg method for importing Git projects, but since I am not currently developing in Pharo, I'm not sure what that is. 

If you find out, please let me know and I will update the documentation (or submit a pull request if you feel so inclined).

**Comment by Toni-zgz** [comment]
Solved. I've installed by hand dependencies and after that smallkanren.

**Comment by emdonahue** [comment]
Will at least take off the install instructions then.
